//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCP.Edu.Pe.SoftProg.Web.SoftProgWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="SoftProgWS.AreaWS")]
    public interface AreaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreaWS/obtenerRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreaWS/obtenerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modeloBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerResponse obtener(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreaWS/obtenerRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreaWS/obtenerResponse")]
        System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerResponse> obtenerAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreaWS/eliminarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreaWS/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modeloBase))]
        PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarResponse eliminar(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreaWS/eliminarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreaWS/eliminarResponse")]
        System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarResponse> eliminarAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarRequest request);
        
        // CODEGEN: Parameter 'area' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreaWS/guardarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreaWS/guardarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modeloBase))]
        PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarResponse guardar(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreaWS/guardarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreaWS/guardarResponse")]
        System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarResponse> guardarAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreaWS/listarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreaWS/listarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modeloBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarResponse listar(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreaWS/listarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreaWS/listarResponse")]
        System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarResponse> listarAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class area : modeloBase {
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(area))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class modeloBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerRequest() {
        }
        
        public obtenerRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area @return;
        
        public obtenerResponse() {
        }
        
        public obtenerResponse(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        public eliminarResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estado {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificar,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area area;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.estado estado;
        
        public guardarRequest() {
        }
        
        public guardarRequest(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area area, PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.estado estado) {
            this.area = area;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarResponse {
        
        public guardarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRequest {
        
        public listarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreaWSChannel : PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreaWSClient : System.ServiceModel.ClientBase<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS>, PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS {
        
        public AreaWSClient() {
        }
        
        public AreaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerResponse PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS.obtener(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerRequest request) {
            return base.Channel.obtener(request);
        }
        
        public PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area obtener(int id) {
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerRequest inValue = new PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerRequest();
            inValue.id = id;
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerResponse retVal = ((PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS)(this)).obtener(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerResponse> PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS.obtenerAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerRequest request) {
            return base.Channel.obtenerAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerResponse> obtenerAsync(int id) {
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerRequest inValue = new PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.obtenerRequest();
            inValue.id = id;
            return ((PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS)(this)).obtenerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarResponse PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS.eliminar(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public void eliminar(int id) {
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarRequest inValue = new PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarRequest();
            inValue.id = id;
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarResponse retVal = ((PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS)(this)).eliminar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarResponse> PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS.eliminarAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarResponse> eliminarAsync(int id) {
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarRequest inValue = new PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.eliminarRequest();
            inValue.id = id;
            return ((PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarResponse PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS.guardar(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarRequest request) {
            return base.Channel.guardar(request);
        }
        
        public void guardar(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area area, PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.estado estado) {
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarRequest inValue = new PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarRequest();
            inValue.area = area;
            inValue.estado = estado;
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarResponse retVal = ((PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS)(this)).guardar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarResponse> PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS.guardarAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarRequest request) {
            return base.Channel.guardarAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarResponse> guardarAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area area, PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.estado estado) {
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarRequest inValue = new PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.guardarRequest();
            inValue.area = area;
            inValue.estado = estado;
            return ((PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS)(this)).guardarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarResponse PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS.listar(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.area[] listar() {
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarRequest inValue = new PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarRequest();
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarResponse retVal = ((PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarResponse> PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS.listarAsync(PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarResponse> listarAsync() {
            PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarRequest inValue = new PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.listarRequest();
            return ((PUCP.Edu.Pe.SoftProg.Web.SoftProgWS.AreaWS)(this)).listarAsync(inValue);
        }
    }
}
