//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWS.Clientes
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="SoftProgWS.Clientes.ClientesWS")]
    public interface ClientesWS
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/listarClientesRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/listarClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Clientes.listarClientesResponse listarClientes(SoftProgWS.Clientes.listarClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/listarClientesRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/listarClientesResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.listarClientesResponse> listarClientesAsync(SoftProgWS.Clientes.listarClientesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/obtenerClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/obtenerClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Clientes.obtenerClienteResponse obtenerCliente(SoftProgWS.Clientes.obtenerClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/obtenerClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/obtenerClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.obtenerClienteResponse> obtenerClienteAsync(SoftProgWS.Clientes.obtenerClienteRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/eliminarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/eliminarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.Clientes.eliminarClienteResponse eliminarCliente(SoftProgWS.Clientes.eliminarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/eliminarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/eliminarClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.eliminarClienteResponse> eliminarClienteAsync(SoftProgWS.Clientes.eliminarClienteRequest request);
        
        // CODEGEN: Parameter 'cliente' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/guardarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/guardarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.Clientes.guardarClienteResponse guardarCliente(SoftProgWS.Clientes.guardarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/guardarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/guardarClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.guardarClienteResponse> guardarClienteAsync(SoftProgWS.Clientes.guardarClienteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/buscarClientePorDniRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/buscarClientePorDniResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Clientes.buscarClientePorDniResponse buscarClientePorDni(SoftProgWS.Clientes.buscarClientePorDniRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/buscarClientePorDniRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/buscarClientePorDniResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.buscarClientePorDniResponse> buscarClientePorDniAsync(SoftProgWS.Clientes.buscarClientePorDniRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/buscarClientePorCuentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/buscarClientePorCuentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Clientes.buscarClientePorCuentaResponse buscarClientePorCuenta(SoftProgWS.Clientes.buscarClientePorCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClientesWS/buscarClientePorCuentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClientesWS/buscarClientePorCuentaResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.buscarClientePorCuentaResponse> buscarClientePorCuentaAsync(SoftProgWS.Clientes.buscarClientePorCuentaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cliente : persona
    {
        
        private categoriaCliente categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private double lineaCreditoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaCliente categoria
        {
            get
            {
                return this.categoriaField;
            }
            set
            {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified
        {
            get
            {
                return this.categoriaFieldSpecified;
            }
            set
            {
                this.categoriaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double lineaCredito
        {
            get
            {
                return this.lineaCreditoField;
            }
            set
            {
                this.lineaCreditoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum categoriaCliente
    {
        
        /// <remarks/>
        ESTANDARD,
        
        /// <remarks/>
        PREMIUM,
        
        /// <remarks/>
        ORO,
        
        /// <remarks/>
        PLATA,
        
        /// <remarks/>
        BRONCE,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class persona : registro
    {
        
        private string apellidoPaternoField;
        
        private cuentaUsuario cuentaUsuarioField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cuentaUsuario cuentaUsuario
        {
            get
            {
                return this.cuentaUsuarioField;
            }
            set
            {
                this.cuentaUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified
        {
            get
            {
                return this.fechaNacimientoFieldSpecified;
            }
            set
            {
                this.fechaNacimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified
        {
            get
            {
                return this.generoFieldSpecified;
            }
            set
            {
                this.generoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cuentaUsuario : registro
    {
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentaUsuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class registro
    {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum genero
    {
        
        /// <remarks/>
        MASCULINO,
        
        /// <remarks/>
        FEMENINO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarClientes", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarClientesRequest
    {
        
        public listarClientesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarClientesResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarClientesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Clientes.cliente[] @return;
        
        public listarClientesResponse()
        {
        }
        
        public listarClientesResponse(SoftProgWS.Clientes.cliente[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerClienteRequest()
        {
        }
        
        public obtenerClienteRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Clientes.cliente @return;
        
        public obtenerClienteResponse()
        {
        }
        
        public obtenerClienteResponse(SoftProgWS.Clientes.cliente @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarClienteRequest()
        {
        }
        
        public eliminarClienteRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarClienteResponse
    {
        
        public eliminarClienteResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estado
    {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Clientes.cliente cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Clientes.estado estado;
        
        public guardarClienteRequest()
        {
        }
        
        public guardarClienteRequest(SoftProgWS.Clientes.cliente cliente, SoftProgWS.Clientes.estado estado)
        {
            this.cliente = cliente;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarClienteResponse
    {
        
        public guardarClienteResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarClientePorDni", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarClientePorDniRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        public buscarClientePorDniRequest()
        {
        }
        
        public buscarClientePorDniRequest(string dni)
        {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarClientePorDniResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarClientePorDniResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Clientes.cliente @return;
        
        public buscarClientePorDniResponse()
        {
        }
        
        public buscarClientePorDniResponse(SoftProgWS.Clientes.cliente @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarClientePorCuenta", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarClientePorCuentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuenta;
        
        public buscarClientePorCuentaRequest()
        {
        }
        
        public buscarClientePorCuentaRequest(string cuenta)
        {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarClientePorCuentaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarClientePorCuentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Clientes.cliente @return;
        
        public buscarClientePorCuentaResponse()
        {
        }
        
        public buscarClientePorCuentaResponse(SoftProgWS.Clientes.cliente @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ClientesWSChannel : SoftProgWS.Clientes.ClientesWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ClientesWSClient : System.ServiceModel.ClientBase<SoftProgWS.Clientes.ClientesWS>, SoftProgWS.Clientes.ClientesWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClientesWSClient() : 
                base(ClientesWSClient.GetDefaultBinding(), ClientesWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ClientesWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientesWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ClientesWSClient.GetBindingForEndpoint(endpointConfiguration), ClientesWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientesWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClientesWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientesWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClientesWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Clientes.listarClientesResponse SoftProgWS.Clientes.ClientesWS.listarClientes(SoftProgWS.Clientes.listarClientesRequest request)
        {
            return base.Channel.listarClientes(request);
        }
        
        public SoftProgWS.Clientes.cliente[] listarClientes()
        {
            SoftProgWS.Clientes.listarClientesRequest inValue = new SoftProgWS.Clientes.listarClientesRequest();
            SoftProgWS.Clientes.listarClientesResponse retVal = ((SoftProgWS.Clientes.ClientesWS)(this)).listarClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.listarClientesResponse> SoftProgWS.Clientes.ClientesWS.listarClientesAsync(SoftProgWS.Clientes.listarClientesRequest request)
        {
            return base.Channel.listarClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Clientes.listarClientesResponse> listarClientesAsync()
        {
            SoftProgWS.Clientes.listarClientesRequest inValue = new SoftProgWS.Clientes.listarClientesRequest();
            return ((SoftProgWS.Clientes.ClientesWS)(this)).listarClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Clientes.obtenerClienteResponse SoftProgWS.Clientes.ClientesWS.obtenerCliente(SoftProgWS.Clientes.obtenerClienteRequest request)
        {
            return base.Channel.obtenerCliente(request);
        }
        
        public SoftProgWS.Clientes.cliente obtenerCliente(int id)
        {
            SoftProgWS.Clientes.obtenerClienteRequest inValue = new SoftProgWS.Clientes.obtenerClienteRequest();
            inValue.id = id;
            SoftProgWS.Clientes.obtenerClienteResponse retVal = ((SoftProgWS.Clientes.ClientesWS)(this)).obtenerCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.obtenerClienteResponse> SoftProgWS.Clientes.ClientesWS.obtenerClienteAsync(SoftProgWS.Clientes.obtenerClienteRequest request)
        {
            return base.Channel.obtenerClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Clientes.obtenerClienteResponse> obtenerClienteAsync(int id)
        {
            SoftProgWS.Clientes.obtenerClienteRequest inValue = new SoftProgWS.Clientes.obtenerClienteRequest();
            inValue.id = id;
            return ((SoftProgWS.Clientes.ClientesWS)(this)).obtenerClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Clientes.eliminarClienteResponse SoftProgWS.Clientes.ClientesWS.eliminarCliente(SoftProgWS.Clientes.eliminarClienteRequest request)
        {
            return base.Channel.eliminarCliente(request);
        }
        
        public void eliminarCliente(int id)
        {
            SoftProgWS.Clientes.eliminarClienteRequest inValue = new SoftProgWS.Clientes.eliminarClienteRequest();
            inValue.id = id;
            SoftProgWS.Clientes.eliminarClienteResponse retVal = ((SoftProgWS.Clientes.ClientesWS)(this)).eliminarCliente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.eliminarClienteResponse> SoftProgWS.Clientes.ClientesWS.eliminarClienteAsync(SoftProgWS.Clientes.eliminarClienteRequest request)
        {
            return base.Channel.eliminarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Clientes.eliminarClienteResponse> eliminarClienteAsync(int id)
        {
            SoftProgWS.Clientes.eliminarClienteRequest inValue = new SoftProgWS.Clientes.eliminarClienteRequest();
            inValue.id = id;
            return ((SoftProgWS.Clientes.ClientesWS)(this)).eliminarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Clientes.guardarClienteResponse SoftProgWS.Clientes.ClientesWS.guardarCliente(SoftProgWS.Clientes.guardarClienteRequest request)
        {
            return base.Channel.guardarCliente(request);
        }
        
        public void guardarCliente(SoftProgWS.Clientes.cliente cliente, SoftProgWS.Clientes.estado estado)
        {
            SoftProgWS.Clientes.guardarClienteRequest inValue = new SoftProgWS.Clientes.guardarClienteRequest();
            inValue.cliente = cliente;
            inValue.estado = estado;
            SoftProgWS.Clientes.guardarClienteResponse retVal = ((SoftProgWS.Clientes.ClientesWS)(this)).guardarCliente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.guardarClienteResponse> SoftProgWS.Clientes.ClientesWS.guardarClienteAsync(SoftProgWS.Clientes.guardarClienteRequest request)
        {
            return base.Channel.guardarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Clientes.guardarClienteResponse> guardarClienteAsync(SoftProgWS.Clientes.cliente cliente, SoftProgWS.Clientes.estado estado)
        {
            SoftProgWS.Clientes.guardarClienteRequest inValue = new SoftProgWS.Clientes.guardarClienteRequest();
            inValue.cliente = cliente;
            inValue.estado = estado;
            return ((SoftProgWS.Clientes.ClientesWS)(this)).guardarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Clientes.buscarClientePorDniResponse SoftProgWS.Clientes.ClientesWS.buscarClientePorDni(SoftProgWS.Clientes.buscarClientePorDniRequest request)
        {
            return base.Channel.buscarClientePorDni(request);
        }
        
        public SoftProgWS.Clientes.cliente buscarClientePorDni(string dni)
        {
            SoftProgWS.Clientes.buscarClientePorDniRequest inValue = new SoftProgWS.Clientes.buscarClientePorDniRequest();
            inValue.dni = dni;
            SoftProgWS.Clientes.buscarClientePorDniResponse retVal = ((SoftProgWS.Clientes.ClientesWS)(this)).buscarClientePorDni(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.buscarClientePorDniResponse> SoftProgWS.Clientes.ClientesWS.buscarClientePorDniAsync(SoftProgWS.Clientes.buscarClientePorDniRequest request)
        {
            return base.Channel.buscarClientePorDniAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Clientes.buscarClientePorDniResponse> buscarClientePorDniAsync(string dni)
        {
            SoftProgWS.Clientes.buscarClientePorDniRequest inValue = new SoftProgWS.Clientes.buscarClientePorDniRequest();
            inValue.dni = dni;
            return ((SoftProgWS.Clientes.ClientesWS)(this)).buscarClientePorDniAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Clientes.buscarClientePorCuentaResponse SoftProgWS.Clientes.ClientesWS.buscarClientePorCuenta(SoftProgWS.Clientes.buscarClientePorCuentaRequest request)
        {
            return base.Channel.buscarClientePorCuenta(request);
        }
        
        public SoftProgWS.Clientes.cliente buscarClientePorCuenta(string cuenta)
        {
            SoftProgWS.Clientes.buscarClientePorCuentaRequest inValue = new SoftProgWS.Clientes.buscarClientePorCuentaRequest();
            inValue.cuenta = cuenta;
            SoftProgWS.Clientes.buscarClientePorCuentaResponse retVal = ((SoftProgWS.Clientes.ClientesWS)(this)).buscarClientePorCuenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Clientes.buscarClientePorCuentaResponse> SoftProgWS.Clientes.ClientesWS.buscarClientePorCuentaAsync(SoftProgWS.Clientes.buscarClientePorCuentaRequest request)
        {
            return base.Channel.buscarClientePorCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Clientes.buscarClientePorCuentaResponse> buscarClientePorCuentaAsync(string cuenta)
        {
            SoftProgWS.Clientes.buscarClientePorCuentaRequest inValue = new SoftProgWS.Clientes.buscarClientePorCuentaRequest();
            inValue.cuenta = cuenta;
            return ((SoftProgWS.Clientes.ClientesWS)(this)).buscarClientePorCuentaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientesWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientesWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.1:8080/SoftProgWS-1.0-SNAPSHOT/ClientesWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ClientesWSClient.GetBindingForEndpoint(EndpointConfiguration.ClientesWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ClientesWSClient.GetEndpointAddress(EndpointConfiguration.ClientesWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ClientesWSPort,
        }
    }
}
