SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE linea_orden_venta;
TRUNCATE TABLE orden_venta;
TRUNCATE TABLE empleado;
TRUNCATE TABLE cliente;
TRUNCATE TABLE producto;
TRUNCATE TABLE cuenta_usuario;
TRUNCATE TABLE area;

ALTER TABLE area AUTO_INCREMENT = 1;
ALTER TABLE empleado AUTO_INCREMENT = 1;
ALTER TABLE cliente AUTO_INCREMENT = 1;
ALTER TABLE cuenta_usuario AUTO_INCREMENT = 1;
ALTER TABLE producto AUTO_INCREMENT = 1;
ALTER TABLE linea_orden_venta AUTO_INCREMENT = 1;
ALTER TABLE orden_venta AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
