//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWS.Areas
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="SoftProgWS.Areas.AreasWS")]
    public interface AreasWS
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreasWS/listarAreasRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreasWS/listarAreasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Areas.listarAreasResponse listarAreas(SoftProgWS.Areas.listarAreasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreasWS/listarAreasRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreasWS/listarAreasResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Areas.listarAreasResponse> listarAreasAsync(SoftProgWS.Areas.listarAreasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreasWS/obtenerAreaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreasWS/obtenerAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Areas.obtenerAreaResponse obtenerArea(SoftProgWS.Areas.obtenerAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreasWS/obtenerAreaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreasWS/obtenerAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Areas.obtenerAreaResponse> obtenerAreaAsync(SoftProgWS.Areas.obtenerAreaRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreasWS/eliminarAreaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreasWS/eliminarAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.Areas.eliminarAreaResponse eliminarArea(SoftProgWS.Areas.eliminarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreasWS/eliminarAreaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreasWS/eliminarAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Areas.eliminarAreaResponse> eliminarAreaAsync(SoftProgWS.Areas.eliminarAreaRequest request);
        
        // CODEGEN: Parameter 'area' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreasWS/guardarAreaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreasWS/guardarAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.Areas.guardarAreaResponse guardarArea(SoftProgWS.Areas.guardarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/AreasWS/guardarAreaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/AreasWS/guardarAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Areas.guardarAreaResponse> guardarAreaAsync(SoftProgWS.Areas.guardarAreaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class area : registro
    {
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(area))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class registro
    {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAreas", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAreasRequest
    {
        
        public listarAreasRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAreasResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAreasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Areas.area[] @return;
        
        public listarAreasResponse()
        {
        }
        
        public listarAreasResponse(SoftProgWS.Areas.area[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerArea", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerAreaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerAreaRequest()
        {
        }
        
        public obtenerAreaRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAreaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerAreaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Areas.area @return;
        
        public obtenerAreaResponse()
        {
        }
        
        public obtenerAreaResponse(SoftProgWS.Areas.area @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarArea", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarAreaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarAreaRequest()
        {
        }
        
        public eliminarAreaRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAreaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarAreaResponse
    {
        
        public eliminarAreaResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estado
    {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarArea", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarAreaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Areas.area area;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Areas.estado estado;
        
        public guardarAreaRequest()
        {
        }
        
        public guardarAreaRequest(SoftProgWS.Areas.area area, SoftProgWS.Areas.estado estado)
        {
            this.area = area;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarAreaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarAreaResponse
    {
        
        public guardarAreaResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AreasWSChannel : SoftProgWS.Areas.AreasWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AreasWSClient : System.ServiceModel.ClientBase<SoftProgWS.Areas.AreasWS>, SoftProgWS.Areas.AreasWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AreasWSClient() : 
                base(AreasWSClient.GetDefaultBinding(), AreasWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AreasWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AreasWSClient(EndpointConfiguration endpointConfiguration) : 
                base(AreasWSClient.GetBindingForEndpoint(endpointConfiguration), AreasWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AreasWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AreasWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AreasWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AreasWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AreasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Areas.listarAreasResponse SoftProgWS.Areas.AreasWS.listarAreas(SoftProgWS.Areas.listarAreasRequest request)
        {
            return base.Channel.listarAreas(request);
        }
        
        public SoftProgWS.Areas.area[] listarAreas()
        {
            SoftProgWS.Areas.listarAreasRequest inValue = new SoftProgWS.Areas.listarAreasRequest();
            SoftProgWS.Areas.listarAreasResponse retVal = ((SoftProgWS.Areas.AreasWS)(this)).listarAreas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Areas.listarAreasResponse> SoftProgWS.Areas.AreasWS.listarAreasAsync(SoftProgWS.Areas.listarAreasRequest request)
        {
            return base.Channel.listarAreasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Areas.listarAreasResponse> listarAreasAsync()
        {
            SoftProgWS.Areas.listarAreasRequest inValue = new SoftProgWS.Areas.listarAreasRequest();
            return ((SoftProgWS.Areas.AreasWS)(this)).listarAreasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Areas.obtenerAreaResponse SoftProgWS.Areas.AreasWS.obtenerArea(SoftProgWS.Areas.obtenerAreaRequest request)
        {
            return base.Channel.obtenerArea(request);
        }
        
        public SoftProgWS.Areas.area obtenerArea(int id)
        {
            SoftProgWS.Areas.obtenerAreaRequest inValue = new SoftProgWS.Areas.obtenerAreaRequest();
            inValue.id = id;
            SoftProgWS.Areas.obtenerAreaResponse retVal = ((SoftProgWS.Areas.AreasWS)(this)).obtenerArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Areas.obtenerAreaResponse> SoftProgWS.Areas.AreasWS.obtenerAreaAsync(SoftProgWS.Areas.obtenerAreaRequest request)
        {
            return base.Channel.obtenerAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Areas.obtenerAreaResponse> obtenerAreaAsync(int id)
        {
            SoftProgWS.Areas.obtenerAreaRequest inValue = new SoftProgWS.Areas.obtenerAreaRequest();
            inValue.id = id;
            return ((SoftProgWS.Areas.AreasWS)(this)).obtenerAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Areas.eliminarAreaResponse SoftProgWS.Areas.AreasWS.eliminarArea(SoftProgWS.Areas.eliminarAreaRequest request)
        {
            return base.Channel.eliminarArea(request);
        }
        
        public void eliminarArea(int id)
        {
            SoftProgWS.Areas.eliminarAreaRequest inValue = new SoftProgWS.Areas.eliminarAreaRequest();
            inValue.id = id;
            SoftProgWS.Areas.eliminarAreaResponse retVal = ((SoftProgWS.Areas.AreasWS)(this)).eliminarArea(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Areas.eliminarAreaResponse> SoftProgWS.Areas.AreasWS.eliminarAreaAsync(SoftProgWS.Areas.eliminarAreaRequest request)
        {
            return base.Channel.eliminarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Areas.eliminarAreaResponse> eliminarAreaAsync(int id)
        {
            SoftProgWS.Areas.eliminarAreaRequest inValue = new SoftProgWS.Areas.eliminarAreaRequest();
            inValue.id = id;
            return ((SoftProgWS.Areas.AreasWS)(this)).eliminarAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Areas.guardarAreaResponse SoftProgWS.Areas.AreasWS.guardarArea(SoftProgWS.Areas.guardarAreaRequest request)
        {
            return base.Channel.guardarArea(request);
        }
        
        public void guardarArea(SoftProgWS.Areas.area area, SoftProgWS.Areas.estado estado)
        {
            SoftProgWS.Areas.guardarAreaRequest inValue = new SoftProgWS.Areas.guardarAreaRequest();
            inValue.area = area;
            inValue.estado = estado;
            SoftProgWS.Areas.guardarAreaResponse retVal = ((SoftProgWS.Areas.AreasWS)(this)).guardarArea(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Areas.guardarAreaResponse> SoftProgWS.Areas.AreasWS.guardarAreaAsync(SoftProgWS.Areas.guardarAreaRequest request)
        {
            return base.Channel.guardarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Areas.guardarAreaResponse> guardarAreaAsync(SoftProgWS.Areas.area area, SoftProgWS.Areas.estado estado)
        {
            SoftProgWS.Areas.guardarAreaRequest inValue = new SoftProgWS.Areas.guardarAreaRequest();
            inValue.area = area;
            inValue.estado = estado;
            return ((SoftProgWS.Areas.AreasWS)(this)).guardarAreaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AreasWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AreasWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.1:8080/SoftProgWS-1.0-SNAPSHOT/AreasWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AreasWSClient.GetBindingForEndpoint(EndpointConfiguration.AreasWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AreasWSClient.GetEndpointAddress(EndpointConfiguration.AreasWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            AreasWSPort,
        }
    }
}
