//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWS.OrdenesVenta
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="SoftProgWS.OrdenesVenta.OrdenesVentaWS")]
    public interface OrdenesVentaWS
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/listarOrdenesVentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/listarOrdenesVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.OrdenesVenta.listarOrdenesVentaResponse listarOrdenesVenta(SoftProgWS.OrdenesVenta.listarOrdenesVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/listarOrdenesVentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/listarOrdenesVentaResponse")]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.listarOrdenesVentaResponse> listarOrdenesVentaAsync(SoftProgWS.OrdenesVenta.listarOrdenesVentaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/obtenerOrdenVentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/obtenerOrdenVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.OrdenesVenta.obtenerOrdenVentaResponse obtenerOrdenVenta(SoftProgWS.OrdenesVenta.obtenerOrdenVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/obtenerOrdenVentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/obtenerOrdenVentaResponse")]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.obtenerOrdenVentaResponse> obtenerOrdenVentaAsync(SoftProgWS.OrdenesVenta.obtenerOrdenVentaRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/eliminarOrdenVentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/eliminarOrdenVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.OrdenesVenta.eliminarOrdenVentaResponse eliminarOrdenVenta(SoftProgWS.OrdenesVenta.eliminarOrdenVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/eliminarOrdenVentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/eliminarOrdenVentaResponse")]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.eliminarOrdenVentaResponse> eliminarOrdenVentaAsync(SoftProgWS.OrdenesVenta.eliminarOrdenVentaRequest request);
        
        // CODEGEN: Parameter 'ordenventa' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/guardarOrdenVentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/guardarOrdenVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.OrdenesVenta.guardarOrdenVentaResponse guardarOrdenVenta(SoftProgWS.OrdenesVenta.guardarOrdenVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/guardarOrdenVentaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/guardarOrdenVentaResponse")]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.guardarOrdenVentaResponse> guardarOrdenVentaAsync(SoftProgWS.OrdenesVenta.guardarOrdenVentaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/listarOrdenesVentaPorCuentaRe" +
            "quest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/listarOrdenesVentaPorCuentaRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaResponse listarOrdenesVentaPorCuenta(SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/listarOrdenesVentaPorCuentaRe" +
            "quest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenesVentaWS/listarOrdenesVentaPorCuentaRe" +
            "sponse")]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaResponse> listarOrdenesVentaPorCuentaAsync(SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class ordenVenta : registro
    {
        
        private cliente clienteField;
        
        private empleado empleadoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private lineaOrdenVenta[] lineasField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public empleado empleado
        {
            get
            {
                return this.empleadoField;
            }
            set
            {
                this.empleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified
        {
            get
            {
                return this.fechaFieldSpecified;
            }
            set
            {
                this.fechaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public lineaOrdenVenta[] lineas
        {
            get
            {
                return this.lineasField;
            }
            set
            {
                this.lineasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cliente : persona
    {
        
        private categoriaCliente categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private double lineaCreditoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaCliente categoria
        {
            get
            {
                return this.categoriaField;
            }
            set
            {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified
        {
            get
            {
                return this.categoriaFieldSpecified;
            }
            set
            {
                this.categoriaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double lineaCredito
        {
            get
            {
                return this.lineaCreditoField;
            }
            set
            {
                this.lineaCreditoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum categoriaCliente
    {
        
        /// <remarks/>
        ESTANDARD,
        
        /// <remarks/>
        PREMIUM,
        
        /// <remarks/>
        ORO,
        
        /// <remarks/>
        PLATA,
        
        /// <remarks/>
        BRONCE,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class persona : registro
    {
        
        private string apellidoPaternoField;
        
        private cuentaUsuario cuentaUsuarioField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cuentaUsuario cuentaUsuario
        {
            get
            {
                return this.cuentaUsuarioField;
            }
            set
            {
                this.cuentaUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified
        {
            get
            {
                return this.fechaNacimientoFieldSpecified;
            }
            set
            {
                this.fechaNacimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified
        {
            get
            {
                return this.generoFieldSpecified;
            }
            set
            {
                this.generoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cuentaUsuario : registro
    {
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(producto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lineaOrdenVenta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(area))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentaUsuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ordenVenta))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class registro
    {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class producto : registro
    {
        
        private string nombreField;
        
        private double precioField;
        
        private unidadMedida unidadMedidaField;
        
        private bool unidadMedidaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public unidadMedida unidadMedida
        {
            get
            {
                return this.unidadMedidaField;
            }
            set
            {
                this.unidadMedidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unidadMedidaSpecified
        {
            get
            {
                return this.unidadMedidaFieldSpecified;
            }
            set
            {
                this.unidadMedidaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum unidadMedida
    {
        
        /// <remarks/>
        UND,
        
        /// <remarks/>
        Kilos,
        
        /// <remarks/>
        Onzas,
        
        /// <remarks/>
        Litros,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class lineaOrdenVenta : registro
    {
        
        private int cantidadField;
        
        private producto productoField;
        
        private double subTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public producto producto
        {
            get
            {
                return this.productoField;
            }
            set
            {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double subTotal
        {
            get
            {
                return this.subTotalField;
            }
            set
            {
                this.subTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class area : registro
    {
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum genero
    {
        
        /// <remarks/>
        MASCULINO,
        
        /// <remarks/>
        FEMENINO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class empleado : persona
    {
        
        private area areaField;
        
        private cargo cargoField;
        
        private bool cargoFieldSpecified;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public area area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cargo cargo
        {
            get
            {
                return this.cargoField;
            }
            set
            {
                this.cargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cargoSpecified
        {
            get
            {
                return this.cargoFieldSpecified;
            }
            set
            {
                this.cargoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double sueldo
        {
            get
            {
                return this.sueldoField;
            }
            set
            {
                this.sueldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum cargo
    {
        
        /// <remarks/>
        GERENTE,
        
        /// <remarks/>
        DIRECTOR,
        
        /// <remarks/>
        SUBDIRECTOR,
        
        /// <remarks/>
        ASISTENTE,
        
        /// <remarks/>
        TECNICO,
        
        /// <remarks/>
        VENDEDOR_SENIOR,
        
        /// <remarks/>
        EJECUTIVO_COMERCIAL,
        
        /// <remarks/>
        ANALISTA_RRHH,
        
        /// <remarks/>
        ENCARGADO_ALMACEN,
        
        /// <remarks/>
        CONTADOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesVenta", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesVentaRequest
    {
        
        public listarOrdenesVentaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesVentaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesVentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.OrdenesVenta.ordenVenta[] @return;
        
        public listarOrdenesVentaResponse()
        {
        }
        
        public listarOrdenesVentaResponse(SoftProgWS.OrdenesVenta.ordenVenta[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenVenta", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerOrdenVentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerOrdenVentaRequest()
        {
        }
        
        public obtenerOrdenVentaRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenVentaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerOrdenVentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.OrdenesVenta.ordenVenta @return;
        
        public obtenerOrdenVentaResponse()
        {
        }
        
        public obtenerOrdenVentaResponse(SoftProgWS.OrdenesVenta.ordenVenta @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenVenta", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenVentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarOrdenVentaRequest()
        {
        }
        
        public eliminarOrdenVentaRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenVentaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenVentaResponse
    {
        
        public eliminarOrdenVentaResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estado
    {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarOrdenVenta", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarOrdenVentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.OrdenesVenta.ordenVenta ordenventa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.OrdenesVenta.estado estado;
        
        public guardarOrdenVentaRequest()
        {
        }
        
        public guardarOrdenVentaRequest(SoftProgWS.OrdenesVenta.ordenVenta ordenventa, SoftProgWS.OrdenesVenta.estado estado)
        {
            this.ordenventa = ordenventa;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarOrdenVentaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarOrdenVentaResponse
    {
        
        public guardarOrdenVentaResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesVentaPorCuenta", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesVentaPorCuentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public listarOrdenesVentaPorCuentaRequest()
        {
        }
        
        public listarOrdenesVentaPorCuentaRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesVentaPorCuentaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesVentaPorCuentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.OrdenesVenta.ordenVenta[] @return;
        
        public listarOrdenesVentaPorCuentaResponse()
        {
        }
        
        public listarOrdenesVentaPorCuentaResponse(SoftProgWS.OrdenesVenta.ordenVenta[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface OrdenesVentaWSChannel : SoftProgWS.OrdenesVenta.OrdenesVentaWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class OrdenesVentaWSClient : System.ServiceModel.ClientBase<SoftProgWS.OrdenesVenta.OrdenesVentaWS>, SoftProgWS.OrdenesVenta.OrdenesVentaWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrdenesVentaWSClient() : 
                base(OrdenesVentaWSClient.GetDefaultBinding(), OrdenesVentaWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OrdenesVentaWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdenesVentaWSClient(EndpointConfiguration endpointConfiguration) : 
                base(OrdenesVentaWSClient.GetBindingForEndpoint(endpointConfiguration), OrdenesVentaWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdenesVentaWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrdenesVentaWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdenesVentaWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrdenesVentaWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdenesVentaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.OrdenesVenta.listarOrdenesVentaResponse SoftProgWS.OrdenesVenta.OrdenesVentaWS.listarOrdenesVenta(SoftProgWS.OrdenesVenta.listarOrdenesVentaRequest request)
        {
            return base.Channel.listarOrdenesVenta(request);
        }
        
        public SoftProgWS.OrdenesVenta.ordenVenta[] listarOrdenesVenta()
        {
            SoftProgWS.OrdenesVenta.listarOrdenesVentaRequest inValue = new SoftProgWS.OrdenesVenta.listarOrdenesVentaRequest();
            SoftProgWS.OrdenesVenta.listarOrdenesVentaResponse retVal = ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).listarOrdenesVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.listarOrdenesVentaResponse> SoftProgWS.OrdenesVenta.OrdenesVentaWS.listarOrdenesVentaAsync(SoftProgWS.OrdenesVenta.listarOrdenesVentaRequest request)
        {
            return base.Channel.listarOrdenesVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.listarOrdenesVentaResponse> listarOrdenesVentaAsync()
        {
            SoftProgWS.OrdenesVenta.listarOrdenesVentaRequest inValue = new SoftProgWS.OrdenesVenta.listarOrdenesVentaRequest();
            return ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).listarOrdenesVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.OrdenesVenta.obtenerOrdenVentaResponse SoftProgWS.OrdenesVenta.OrdenesVentaWS.obtenerOrdenVenta(SoftProgWS.OrdenesVenta.obtenerOrdenVentaRequest request)
        {
            return base.Channel.obtenerOrdenVenta(request);
        }
        
        public SoftProgWS.OrdenesVenta.ordenVenta obtenerOrdenVenta(int id)
        {
            SoftProgWS.OrdenesVenta.obtenerOrdenVentaRequest inValue = new SoftProgWS.OrdenesVenta.obtenerOrdenVentaRequest();
            inValue.id = id;
            SoftProgWS.OrdenesVenta.obtenerOrdenVentaResponse retVal = ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).obtenerOrdenVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.obtenerOrdenVentaResponse> SoftProgWS.OrdenesVenta.OrdenesVentaWS.obtenerOrdenVentaAsync(SoftProgWS.OrdenesVenta.obtenerOrdenVentaRequest request)
        {
            return base.Channel.obtenerOrdenVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.obtenerOrdenVentaResponse> obtenerOrdenVentaAsync(int id)
        {
            SoftProgWS.OrdenesVenta.obtenerOrdenVentaRequest inValue = new SoftProgWS.OrdenesVenta.obtenerOrdenVentaRequest();
            inValue.id = id;
            return ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).obtenerOrdenVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.OrdenesVenta.eliminarOrdenVentaResponse SoftProgWS.OrdenesVenta.OrdenesVentaWS.eliminarOrdenVenta(SoftProgWS.OrdenesVenta.eliminarOrdenVentaRequest request)
        {
            return base.Channel.eliminarOrdenVenta(request);
        }
        
        public void eliminarOrdenVenta(int id)
        {
            SoftProgWS.OrdenesVenta.eliminarOrdenVentaRequest inValue = new SoftProgWS.OrdenesVenta.eliminarOrdenVentaRequest();
            inValue.id = id;
            SoftProgWS.OrdenesVenta.eliminarOrdenVentaResponse retVal = ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).eliminarOrdenVenta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.eliminarOrdenVentaResponse> SoftProgWS.OrdenesVenta.OrdenesVentaWS.eliminarOrdenVentaAsync(SoftProgWS.OrdenesVenta.eliminarOrdenVentaRequest request)
        {
            return base.Channel.eliminarOrdenVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.eliminarOrdenVentaResponse> eliminarOrdenVentaAsync(int id)
        {
            SoftProgWS.OrdenesVenta.eliminarOrdenVentaRequest inValue = new SoftProgWS.OrdenesVenta.eliminarOrdenVentaRequest();
            inValue.id = id;
            return ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).eliminarOrdenVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.OrdenesVenta.guardarOrdenVentaResponse SoftProgWS.OrdenesVenta.OrdenesVentaWS.guardarOrdenVenta(SoftProgWS.OrdenesVenta.guardarOrdenVentaRequest request)
        {
            return base.Channel.guardarOrdenVenta(request);
        }
        
        public void guardarOrdenVenta(SoftProgWS.OrdenesVenta.ordenVenta ordenventa, SoftProgWS.OrdenesVenta.estado estado)
        {
            SoftProgWS.OrdenesVenta.guardarOrdenVentaRequest inValue = new SoftProgWS.OrdenesVenta.guardarOrdenVentaRequest();
            inValue.ordenventa = ordenventa;
            inValue.estado = estado;
            SoftProgWS.OrdenesVenta.guardarOrdenVentaResponse retVal = ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).guardarOrdenVenta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.guardarOrdenVentaResponse> SoftProgWS.OrdenesVenta.OrdenesVentaWS.guardarOrdenVentaAsync(SoftProgWS.OrdenesVenta.guardarOrdenVentaRequest request)
        {
            return base.Channel.guardarOrdenVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.guardarOrdenVentaResponse> guardarOrdenVentaAsync(SoftProgWS.OrdenesVenta.ordenVenta ordenventa, SoftProgWS.OrdenesVenta.estado estado)
        {
            SoftProgWS.OrdenesVenta.guardarOrdenVentaRequest inValue = new SoftProgWS.OrdenesVenta.guardarOrdenVentaRequest();
            inValue.ordenventa = ordenventa;
            inValue.estado = estado;
            return ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).guardarOrdenVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaResponse SoftProgWS.OrdenesVenta.OrdenesVentaWS.listarOrdenesVentaPorCuenta(SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaRequest request)
        {
            return base.Channel.listarOrdenesVentaPorCuenta(request);
        }
        
        public SoftProgWS.OrdenesVenta.ordenVenta[] listarOrdenesVentaPorCuenta(string arg0)
        {
            SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaRequest inValue = new SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaRequest();
            inValue.arg0 = arg0;
            SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaResponse retVal = ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).listarOrdenesVentaPorCuenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaResponse> SoftProgWS.OrdenesVenta.OrdenesVentaWS.listarOrdenesVentaPorCuentaAsync(SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaRequest request)
        {
            return base.Channel.listarOrdenesVentaPorCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaResponse> listarOrdenesVentaPorCuentaAsync(string arg0)
        {
            SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaRequest inValue = new SoftProgWS.OrdenesVenta.listarOrdenesVentaPorCuentaRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWS.OrdenesVenta.OrdenesVentaWS)(this)).listarOrdenesVentaPorCuentaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrdenesVentaWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrdenesVentaWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.1:8080/SoftProgWS-1.0-SNAPSHOT/OrdenesVentaWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OrdenesVentaWSClient.GetBindingForEndpoint(EndpointConfiguration.OrdenesVentaWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OrdenesVentaWSClient.GetEndpointAddress(EndpointConfiguration.OrdenesVentaWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            OrdenesVentaWSPort,
        }
    }
}
