USE prog3;

SELECT * FROM AREA;
SELECT * FROM CUENTA_USUARIO;
SELECT * FROM EMPLEADO;

DELETE FROM EMPLEADO WHERE ID > 0;
DELETE FROM AREA WHERE ID > 0;
DELETE FROM CUENTA_USUARIO WHERE ID > 0;

ALTER TABLE AREA AUTO_INCREMENT = 1;
ALTER TABLE CUENTA_USUARIO AUTO_INCREMENT = 1;
ALTER TABLE EMPLEADO AUTO_INCREMENT = 1;