//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWS.Productos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="SoftProgWS.Productos.ProductosWS")]
    public interface ProductosWS
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductosWS/listarProductosRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductosWS/listarProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Productos.listarProductosResponse listarProductos(SoftProgWS.Productos.listarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductosWS/listarProductosRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductosWS/listarProductosResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Productos.listarProductosResponse> listarProductosAsync(SoftProgWS.Productos.listarProductosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductosWS/obtenerProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductosWS/obtenerProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Productos.obtenerProductoResponse obtenerProducto(SoftProgWS.Productos.obtenerProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductosWS/obtenerProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductosWS/obtenerProductoResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Productos.obtenerProductoResponse> obtenerProductoAsync(SoftProgWS.Productos.obtenerProductoRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductosWS/eliminarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductosWS/eliminarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.Productos.eliminarProductoResponse eliminarProducto(SoftProgWS.Productos.eliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductosWS/eliminarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductosWS/eliminarProductoResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Productos.eliminarProductoResponse> eliminarProductoAsync(SoftProgWS.Productos.eliminarProductoRequest request);
        
        // CODEGEN: Parameter 'producto' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductosWS/guardarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductosWS/guardarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.Productos.guardarProductoResponse guardarProducto(SoftProgWS.Productos.guardarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductosWS/guardarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductosWS/guardarProductoResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Productos.guardarProductoResponse> guardarProductoAsync(SoftProgWS.Productos.guardarProductoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class producto : registro
    {
        
        private string nombreField;
        
        private double precioField;
        
        private unidadMedida unidadMedidaField;
        
        private bool unidadMedidaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public unidadMedida unidadMedida
        {
            get
            {
                return this.unidadMedidaField;
            }
            set
            {
                this.unidadMedidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unidadMedidaSpecified
        {
            get
            {
                return this.unidadMedidaFieldSpecified;
            }
            set
            {
                this.unidadMedidaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum unidadMedida
    {
        
        /// <remarks/>
        UND,
        
        /// <remarks/>
        Kilos,
        
        /// <remarks/>
        Onzas,
        
        /// <remarks/>
        Litros,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(producto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class registro
    {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductos", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosRequest
    {
        
        public listarProductosRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Productos.producto[] @return;
        
        public listarProductosResponse()
        {
        }
        
        public listarProductosResponse(SoftProgWS.Productos.producto[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerProductoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerProductoRequest()
        {
        }
        
        public obtenerProductoRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerProductoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Productos.producto @return;
        
        public obtenerProductoResponse()
        {
        }
        
        public obtenerProductoResponse(SoftProgWS.Productos.producto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarProductoRequest()
        {
        }
        
        public eliminarProductoRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoResponse
    {
        
        public eliminarProductoResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estado
    {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarProductoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Productos.producto producto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Productos.estado estado;
        
        public guardarProductoRequest()
        {
        }
        
        public guardarProductoRequest(SoftProgWS.Productos.producto producto, SoftProgWS.Productos.estado estado)
        {
            this.producto = producto;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarProductoResponse
    {
        
        public guardarProductoResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ProductosWSChannel : SoftProgWS.Productos.ProductosWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProductosWSClient : System.ServiceModel.ClientBase<SoftProgWS.Productos.ProductosWS>, SoftProgWS.Productos.ProductosWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductosWSClient() : 
                base(ProductosWSClient.GetDefaultBinding(), ProductosWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProductosWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductosWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductosWSClient.GetBindingForEndpoint(endpointConfiguration), ProductosWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductosWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductosWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductosWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductosWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Productos.listarProductosResponse SoftProgWS.Productos.ProductosWS.listarProductos(SoftProgWS.Productos.listarProductosRequest request)
        {
            return base.Channel.listarProductos(request);
        }
        
        public SoftProgWS.Productos.producto[] listarProductos()
        {
            SoftProgWS.Productos.listarProductosRequest inValue = new SoftProgWS.Productos.listarProductosRequest();
            SoftProgWS.Productos.listarProductosResponse retVal = ((SoftProgWS.Productos.ProductosWS)(this)).listarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Productos.listarProductosResponse> SoftProgWS.Productos.ProductosWS.listarProductosAsync(SoftProgWS.Productos.listarProductosRequest request)
        {
            return base.Channel.listarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Productos.listarProductosResponse> listarProductosAsync()
        {
            SoftProgWS.Productos.listarProductosRequest inValue = new SoftProgWS.Productos.listarProductosRequest();
            return ((SoftProgWS.Productos.ProductosWS)(this)).listarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Productos.obtenerProductoResponse SoftProgWS.Productos.ProductosWS.obtenerProducto(SoftProgWS.Productos.obtenerProductoRequest request)
        {
            return base.Channel.obtenerProducto(request);
        }
        
        public SoftProgWS.Productos.producto obtenerProducto(int id)
        {
            SoftProgWS.Productos.obtenerProductoRequest inValue = new SoftProgWS.Productos.obtenerProductoRequest();
            inValue.id = id;
            SoftProgWS.Productos.obtenerProductoResponse retVal = ((SoftProgWS.Productos.ProductosWS)(this)).obtenerProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Productos.obtenerProductoResponse> SoftProgWS.Productos.ProductosWS.obtenerProductoAsync(SoftProgWS.Productos.obtenerProductoRequest request)
        {
            return base.Channel.obtenerProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Productos.obtenerProductoResponse> obtenerProductoAsync(int id)
        {
            SoftProgWS.Productos.obtenerProductoRequest inValue = new SoftProgWS.Productos.obtenerProductoRequest();
            inValue.id = id;
            return ((SoftProgWS.Productos.ProductosWS)(this)).obtenerProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Productos.eliminarProductoResponse SoftProgWS.Productos.ProductosWS.eliminarProducto(SoftProgWS.Productos.eliminarProductoRequest request)
        {
            return base.Channel.eliminarProducto(request);
        }
        
        public void eliminarProducto(int id)
        {
            SoftProgWS.Productos.eliminarProductoRequest inValue = new SoftProgWS.Productos.eliminarProductoRequest();
            inValue.id = id;
            SoftProgWS.Productos.eliminarProductoResponse retVal = ((SoftProgWS.Productos.ProductosWS)(this)).eliminarProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Productos.eliminarProductoResponse> SoftProgWS.Productos.ProductosWS.eliminarProductoAsync(SoftProgWS.Productos.eliminarProductoRequest request)
        {
            return base.Channel.eliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Productos.eliminarProductoResponse> eliminarProductoAsync(int id)
        {
            SoftProgWS.Productos.eliminarProductoRequest inValue = new SoftProgWS.Productos.eliminarProductoRequest();
            inValue.id = id;
            return ((SoftProgWS.Productos.ProductosWS)(this)).eliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Productos.guardarProductoResponse SoftProgWS.Productos.ProductosWS.guardarProducto(SoftProgWS.Productos.guardarProductoRequest request)
        {
            return base.Channel.guardarProducto(request);
        }
        
        public void guardarProducto(SoftProgWS.Productos.producto producto, SoftProgWS.Productos.estado estado)
        {
            SoftProgWS.Productos.guardarProductoRequest inValue = new SoftProgWS.Productos.guardarProductoRequest();
            inValue.producto = producto;
            inValue.estado = estado;
            SoftProgWS.Productos.guardarProductoResponse retVal = ((SoftProgWS.Productos.ProductosWS)(this)).guardarProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Productos.guardarProductoResponse> SoftProgWS.Productos.ProductosWS.guardarProductoAsync(SoftProgWS.Productos.guardarProductoRequest request)
        {
            return base.Channel.guardarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Productos.guardarProductoResponse> guardarProductoAsync(SoftProgWS.Productos.producto producto, SoftProgWS.Productos.estado estado)
        {
            SoftProgWS.Productos.guardarProductoRequest inValue = new SoftProgWS.Productos.guardarProductoRequest();
            inValue.producto = producto;
            inValue.estado = estado;
            return ((SoftProgWS.Productos.ProductosWS)(this)).guardarProductoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductosWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductosWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.1:8080/SoftProgWS-1.0-SNAPSHOT/ProductosWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProductosWSClient.GetBindingForEndpoint(EndpointConfiguration.ProductosWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProductosWSClient.GetEndpointAddress(EndpointConfiguration.ProductosWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ProductosWSPort,
        }
    }
}
