USE prog3;

CREATE TABLE AREA (
	id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL, 
    nombre VARCHAR(50) NOT NULL, 
    activo BIT NOT NULL DEFAULT 0
);

CREATE TABLE CUENTA_USUARIO (
	id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL, 
    userName VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL, 
    activo BIT NOT NULL DEFAULT 0
);

CREATE TABLE EMPLEADO (
	id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL, 
    idArea INT NOT NULL, 
    idCuentaUsuario INT NOT NULL, 
    dni CHAR(8) NOT NULL, 
    nombre VARCHAR(50) NOT NULL, 
    apellidoPaterno VARCHAR(50) NOT NULL, 
    genero CHAR NOT NULL, 
    fechaNacimiento DATE NOT NULL, 
    cargo VARCHAR(50) NOT NULL, 
    sueldo DECIMAL(10, 2) NOT NULL, 
    activo BIT NOT NULL DEFAULT 0
);

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_AREA 
FOREIGN KEY (idArea) REFERENCES AREA(id);

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_CUENTA_USUARIO
FOREIGN KEY (idCuentaUsuario) REFERENCES CUENTA_USUARIO(id);