//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWS.CuentasUsuario
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="SoftProgWS.CuentasUsuario.CuentasUsuarioWS")]
    public interface CuentasUsuarioWS
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/loginRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.CuentasUsuario.loginResponse login(SoftProgWS.CuentasUsuario.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/loginRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/loginResponse")]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.loginResponse> loginAsync(SoftProgWS.CuentasUsuario.loginRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/listarCuentasUsuarioRequest" +
            "", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/listarCuentasUsuarioRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.CuentasUsuario.listarCuentasUsuarioResponse listarCuentasUsuario(SoftProgWS.CuentasUsuario.listarCuentasUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/listarCuentasUsuarioRequest" +
            "", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/listarCuentasUsuarioRespons" +
            "e")]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.listarCuentasUsuarioResponse> listarCuentasUsuarioAsync(SoftProgWS.CuentasUsuario.listarCuentasUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/obtenerCuentaUsuarioRequest" +
            "", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/obtenerCuentaUsuarioRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioResponse obtenerCuentaUsuario(SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/obtenerCuentaUsuarioRequest" +
            "", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/obtenerCuentaUsuarioRespons" +
            "e")]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioResponse> obtenerCuentaUsuarioAsync(SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/eliminarCuentaUsuarioReques" +
            "t", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/eliminarCuentaUsuarioRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioResponse eliminarCuentaUsuario(SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/eliminarCuentaUsuarioReques" +
            "t", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/eliminarCuentaUsuarioRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioResponse> eliminarCuentaUsuarioAsync(SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioRequest request);
        
        // CODEGEN: Parameter 'area' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/guardarCuentaUsuarioRequest" +
            "", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/guardarCuentaUsuarioRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.CuentasUsuario.guardarCuentaUsuarioResponse guardarCuentaUsuario(SoftProgWS.CuentasUsuario.guardarCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/guardarCuentaUsuarioRequest" +
            "", ReplyAction="http://services.softprog.pucp.edu.pe/CuentasUsuarioWS/guardarCuentaUsuarioRespons" +
            "e")]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.guardarCuentaUsuarioResponse> guardarCuentaUsuarioAsync(SoftProgWS.CuentasUsuario.guardarCuentaUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public loginRequest()
        {
        }
        
        public loginRequest(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public loginResponse()
        {
        }
        
        public loginResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cuentaUsuario : registro
    {
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentaUsuario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class registro
    {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuentasUsuario", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCuentasUsuarioRequest
    {
        
        public listarCuentasUsuarioRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuentasUsuarioResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCuentasUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.CuentasUsuario.cuentaUsuario[] @return;
        
        public listarCuentasUsuarioResponse()
        {
        }
        
        public listarCuentasUsuarioResponse(SoftProgWS.CuentasUsuario.cuentaUsuario[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentaUsuario", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentaUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerCuentaUsuarioRequest()
        {
        }
        
        public obtenerCuentaUsuarioRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentaUsuarioResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentaUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.CuentasUsuario.cuentaUsuario @return;
        
        public obtenerCuentaUsuarioResponse()
        {
        }
        
        public obtenerCuentaUsuarioResponse(SoftProgWS.CuentasUsuario.cuentaUsuario @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaUsuario", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuentaUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarCuentaUsuarioRequest()
        {
        }
        
        public eliminarCuentaUsuarioRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaUsuarioResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuentaUsuarioResponse
    {
        
        public eliminarCuentaUsuarioResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estado
    {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarCuentaUsuario", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarCuentaUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.CuentasUsuario.cuentaUsuario area;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.CuentasUsuario.estado estado;
        
        public guardarCuentaUsuarioRequest()
        {
        }
        
        public guardarCuentaUsuarioRequest(SoftProgWS.CuentasUsuario.cuentaUsuario area, SoftProgWS.CuentasUsuario.estado estado)
        {
            this.area = area;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarCuentaUsuarioResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarCuentaUsuarioResponse
    {
        
        public guardarCuentaUsuarioResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface CuentasUsuarioWSChannel : SoftProgWS.CuentasUsuario.CuentasUsuarioWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CuentasUsuarioWSClient : System.ServiceModel.ClientBase<SoftProgWS.CuentasUsuario.CuentasUsuarioWS>, SoftProgWS.CuentasUsuario.CuentasUsuarioWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CuentasUsuarioWSClient() : 
                base(CuentasUsuarioWSClient.GetDefaultBinding(), CuentasUsuarioWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CuentasUsuarioWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CuentasUsuarioWSClient(EndpointConfiguration endpointConfiguration) : 
                base(CuentasUsuarioWSClient.GetBindingForEndpoint(endpointConfiguration), CuentasUsuarioWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CuentasUsuarioWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CuentasUsuarioWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CuentasUsuarioWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CuentasUsuarioWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CuentasUsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.CuentasUsuario.loginResponse SoftProgWS.CuentasUsuario.CuentasUsuarioWS.login(SoftProgWS.CuentasUsuario.loginRequest request)
        {
            return base.Channel.login(request);
        }
        
        public bool login(string userName, string password)
        {
            SoftProgWS.CuentasUsuario.loginRequest inValue = new SoftProgWS.CuentasUsuario.loginRequest();
            inValue.userName = userName;
            inValue.password = password;
            SoftProgWS.CuentasUsuario.loginResponse retVal = ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.loginResponse> SoftProgWS.CuentasUsuario.CuentasUsuarioWS.loginAsync(SoftProgWS.CuentasUsuario.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.loginResponse> loginAsync(string userName, string password)
        {
            SoftProgWS.CuentasUsuario.loginRequest inValue = new SoftProgWS.CuentasUsuario.loginRequest();
            inValue.userName = userName;
            inValue.password = password;
            return ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.CuentasUsuario.listarCuentasUsuarioResponse SoftProgWS.CuentasUsuario.CuentasUsuarioWS.listarCuentasUsuario(SoftProgWS.CuentasUsuario.listarCuentasUsuarioRequest request)
        {
            return base.Channel.listarCuentasUsuario(request);
        }
        
        public SoftProgWS.CuentasUsuario.cuentaUsuario[] listarCuentasUsuario()
        {
            SoftProgWS.CuentasUsuario.listarCuentasUsuarioRequest inValue = new SoftProgWS.CuentasUsuario.listarCuentasUsuarioRequest();
            SoftProgWS.CuentasUsuario.listarCuentasUsuarioResponse retVal = ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).listarCuentasUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.listarCuentasUsuarioResponse> SoftProgWS.CuentasUsuario.CuentasUsuarioWS.listarCuentasUsuarioAsync(SoftProgWS.CuentasUsuario.listarCuentasUsuarioRequest request)
        {
            return base.Channel.listarCuentasUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.listarCuentasUsuarioResponse> listarCuentasUsuarioAsync()
        {
            SoftProgWS.CuentasUsuario.listarCuentasUsuarioRequest inValue = new SoftProgWS.CuentasUsuario.listarCuentasUsuarioRequest();
            return ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).listarCuentasUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioResponse SoftProgWS.CuentasUsuario.CuentasUsuarioWS.obtenerCuentaUsuario(SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioRequest request)
        {
            return base.Channel.obtenerCuentaUsuario(request);
        }
        
        public SoftProgWS.CuentasUsuario.cuentaUsuario obtenerCuentaUsuario(int id)
        {
            SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioRequest inValue = new SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioRequest();
            inValue.id = id;
            SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioResponse retVal = ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).obtenerCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioResponse> SoftProgWS.CuentasUsuario.CuentasUsuarioWS.obtenerCuentaUsuarioAsync(SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioRequest request)
        {
            return base.Channel.obtenerCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioResponse> obtenerCuentaUsuarioAsync(int id)
        {
            SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioRequest inValue = new SoftProgWS.CuentasUsuario.obtenerCuentaUsuarioRequest();
            inValue.id = id;
            return ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).obtenerCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioResponse SoftProgWS.CuentasUsuario.CuentasUsuarioWS.eliminarCuentaUsuario(SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioRequest request)
        {
            return base.Channel.eliminarCuentaUsuario(request);
        }
        
        public void eliminarCuentaUsuario(int id)
        {
            SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioRequest inValue = new SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioRequest();
            inValue.id = id;
            SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioResponse retVal = ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).eliminarCuentaUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioResponse> SoftProgWS.CuentasUsuario.CuentasUsuarioWS.eliminarCuentaUsuarioAsync(SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioRequest request)
        {
            return base.Channel.eliminarCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioResponse> eliminarCuentaUsuarioAsync(int id)
        {
            SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioRequest inValue = new SoftProgWS.CuentasUsuario.eliminarCuentaUsuarioRequest();
            inValue.id = id;
            return ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).eliminarCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.CuentasUsuario.guardarCuentaUsuarioResponse SoftProgWS.CuentasUsuario.CuentasUsuarioWS.guardarCuentaUsuario(SoftProgWS.CuentasUsuario.guardarCuentaUsuarioRequest request)
        {
            return base.Channel.guardarCuentaUsuario(request);
        }
        
        public void guardarCuentaUsuario(SoftProgWS.CuentasUsuario.cuentaUsuario area, SoftProgWS.CuentasUsuario.estado estado)
        {
            SoftProgWS.CuentasUsuario.guardarCuentaUsuarioRequest inValue = new SoftProgWS.CuentasUsuario.guardarCuentaUsuarioRequest();
            inValue.area = area;
            inValue.estado = estado;
            SoftProgWS.CuentasUsuario.guardarCuentaUsuarioResponse retVal = ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).guardarCuentaUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.guardarCuentaUsuarioResponse> SoftProgWS.CuentasUsuario.CuentasUsuarioWS.guardarCuentaUsuarioAsync(SoftProgWS.CuentasUsuario.guardarCuentaUsuarioRequest request)
        {
            return base.Channel.guardarCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.CuentasUsuario.guardarCuentaUsuarioResponse> guardarCuentaUsuarioAsync(SoftProgWS.CuentasUsuario.cuentaUsuario area, SoftProgWS.CuentasUsuario.estado estado)
        {
            SoftProgWS.CuentasUsuario.guardarCuentaUsuarioRequest inValue = new SoftProgWS.CuentasUsuario.guardarCuentaUsuarioRequest();
            inValue.area = area;
            inValue.estado = estado;
            return ((SoftProgWS.CuentasUsuario.CuentasUsuarioWS)(this)).guardarCuentaUsuarioAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CuentasUsuarioWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CuentasUsuarioWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.1:8080/SoftProgWS-1.0-SNAPSHOT/CuentasUsuarioWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CuentasUsuarioWSClient.GetBindingForEndpoint(EndpointConfiguration.CuentasUsuarioWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CuentasUsuarioWSClient.GetEndpointAddress(EndpointConfiguration.CuentasUsuarioWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CuentasUsuarioWSPort,
        }
    }
}
