//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWS.Empleados
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="SoftProgWS.Empleados.EmpleadosWS")]
    public interface EmpleadosWS
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/listarEmpleadosRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/listarEmpleadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Empleados.listarEmpleadosResponse listarEmpleados(SoftProgWS.Empleados.listarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/listarEmpleadosRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/listarEmpleadosResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.listarEmpleadosResponse> listarEmpleadosAsync(SoftProgWS.Empleados.listarEmpleadosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/obtenerEmpleaedoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/obtenerEmpleaedoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Empleados.obtenerEmpleaedoResponse obtenerEmpleaedo(SoftProgWS.Empleados.obtenerEmpleaedoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/obtenerEmpleaedoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/obtenerEmpleaedoResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.obtenerEmpleaedoResponse> obtenerEmpleaedoAsync(SoftProgWS.Empleados.obtenerEmpleaedoRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/eliminarEmpleadoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/eliminarEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.Empleados.eliminarEmpleadoResponse eliminarEmpleado(SoftProgWS.Empleados.eliminarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/eliminarEmpleadoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/eliminarEmpleadoResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.eliminarEmpleadoResponse> eliminarEmpleadoAsync(SoftProgWS.Empleados.eliminarEmpleadoRequest request);
        
        // CODEGEN: Parameter 'empleado' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/guardarEmpleadoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/guardarEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWS.Empleados.guardarEmpleadoResponse guardarEmpleado(SoftProgWS.Empleados.guardarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/guardarEmpleadoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/guardarEmpleadoResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.guardarEmpleadoResponse> guardarEmpleadoAsync(SoftProgWS.Empleados.guardarEmpleadoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/buscarEmpleadoPorDniRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/buscarEmpleadoPorDniResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWS.Empleados.buscarEmpleadoPorDniResponse buscarEmpleadoPorDni(SoftProgWS.Empleados.buscarEmpleadoPorDniRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpleadosWS/buscarEmpleadoPorDniRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpleadosWS/buscarEmpleadoPorDniResponse")]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.buscarEmpleadoPorDniResponse> buscarEmpleadoPorDniAsync(SoftProgWS.Empleados.buscarEmpleadoPorDniRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class empleado : persona
    {
        
        private area areaField;
        
        private cargo cargoField;
        
        private bool cargoFieldSpecified;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public area area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cargo cargo
        {
            get
            {
                return this.cargoField;
            }
            set
            {
                this.cargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cargoSpecified
        {
            get
            {
                return this.cargoFieldSpecified;
            }
            set
            {
                this.cargoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double sueldo
        {
            get
            {
                return this.sueldoField;
            }
            set
            {
                this.sueldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class area : registro
    {
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(area))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentaUsuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class registro
    {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cuentaUsuario : registro
    {
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public abstract partial class persona : registro
    {
        
        private string apellidoPaternoField;
        
        private cuentaUsuario cuentaUsuarioField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cuentaUsuario cuentaUsuario
        {
            get
            {
                return this.cuentaUsuarioField;
            }
            set
            {
                this.cuentaUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified
        {
            get
            {
                return this.fechaNacimientoFieldSpecified;
            }
            set
            {
                this.fechaNacimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified
        {
            get
            {
                return this.generoFieldSpecified;
            }
            set
            {
                this.generoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum genero
    {
        
        /// <remarks/>
        MASCULINO,
        
        /// <remarks/>
        FEMENINO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum cargo
    {
        
        /// <remarks/>
        GERENTE,
        
        /// <remarks/>
        DIRECTOR,
        
        /// <remarks/>
        SUBDIRECTOR,
        
        /// <remarks/>
        ASISTENTE,
        
        /// <remarks/>
        TECNICO,
        
        /// <remarks/>
        VENDEDOR_SENIOR,
        
        /// <remarks/>
        EJECUTIVO_COMERCIAL,
        
        /// <remarks/>
        ANALISTA_RRHH,
        
        /// <remarks/>
        ENCARGADO_ALMACEN,
        
        /// <remarks/>
        CONTADOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleados", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpleadosRequest
    {
        
        public listarEmpleadosRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleadosResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpleadosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Empleados.empleado[] @return;
        
        public listarEmpleadosResponse()
        {
        }
        
        public listarEmpleadosResponse(SoftProgWS.Empleados.empleado[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpleaedo", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEmpleaedoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerEmpleaedoRequest()
        {
        }
        
        public obtenerEmpleaedoRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpleaedoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEmpleaedoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Empleados.empleado @return;
        
        public obtenerEmpleaedoResponse()
        {
        }
        
        public obtenerEmpleaedoResponse(SoftProgWS.Empleados.empleado @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpleado", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpleadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarEmpleadoRequest()
        {
        }
        
        public eliminarEmpleadoRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpleadoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpleadoResponse
    {
        
        public eliminarEmpleadoResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estado
    {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarEmpleado", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarEmpleadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Empleados.empleado empleado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Empleados.estado estado;
        
        public guardarEmpleadoRequest()
        {
        }
        
        public guardarEmpleadoRequest(SoftProgWS.Empleados.empleado empleado, SoftProgWS.Empleados.estado estado)
        {
            this.empleado = empleado;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarEmpleadoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarEmpleadoResponse
    {
        
        public guardarEmpleadoResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarEmpleadoPorDni", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarEmpleadoPorDniRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        public buscarEmpleadoPorDniRequest()
        {
        }
        
        public buscarEmpleadoPorDniRequest(string dni)
        {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarEmpleadoPorDniResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarEmpleadoPorDniResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWS.Empleados.empleado @return;
        
        public buscarEmpleadoPorDniResponse()
        {
        }
        
        public buscarEmpleadoPorDniResponse(SoftProgWS.Empleados.empleado @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface EmpleadosWSChannel : SoftProgWS.Empleados.EmpleadosWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EmpleadosWSClient : System.ServiceModel.ClientBase<SoftProgWS.Empleados.EmpleadosWS>, SoftProgWS.Empleados.EmpleadosWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmpleadosWSClient() : 
                base(EmpleadosWSClient.GetDefaultBinding(), EmpleadosWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EmpleadosWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosWSClient(EndpointConfiguration endpointConfiguration) : 
                base(EmpleadosWSClient.GetBindingForEndpoint(endpointConfiguration), EmpleadosWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmpleadosWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmpleadosWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Empleados.listarEmpleadosResponse SoftProgWS.Empleados.EmpleadosWS.listarEmpleados(SoftProgWS.Empleados.listarEmpleadosRequest request)
        {
            return base.Channel.listarEmpleados(request);
        }
        
        public SoftProgWS.Empleados.empleado[] listarEmpleados()
        {
            SoftProgWS.Empleados.listarEmpleadosRequest inValue = new SoftProgWS.Empleados.listarEmpleadosRequest();
            SoftProgWS.Empleados.listarEmpleadosResponse retVal = ((SoftProgWS.Empleados.EmpleadosWS)(this)).listarEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.listarEmpleadosResponse> SoftProgWS.Empleados.EmpleadosWS.listarEmpleadosAsync(SoftProgWS.Empleados.listarEmpleadosRequest request)
        {
            return base.Channel.listarEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Empleados.listarEmpleadosResponse> listarEmpleadosAsync()
        {
            SoftProgWS.Empleados.listarEmpleadosRequest inValue = new SoftProgWS.Empleados.listarEmpleadosRequest();
            return ((SoftProgWS.Empleados.EmpleadosWS)(this)).listarEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Empleados.obtenerEmpleaedoResponse SoftProgWS.Empleados.EmpleadosWS.obtenerEmpleaedo(SoftProgWS.Empleados.obtenerEmpleaedoRequest request)
        {
            return base.Channel.obtenerEmpleaedo(request);
        }
        
        public SoftProgWS.Empleados.empleado obtenerEmpleaedo(int id)
        {
            SoftProgWS.Empleados.obtenerEmpleaedoRequest inValue = new SoftProgWS.Empleados.obtenerEmpleaedoRequest();
            inValue.id = id;
            SoftProgWS.Empleados.obtenerEmpleaedoResponse retVal = ((SoftProgWS.Empleados.EmpleadosWS)(this)).obtenerEmpleaedo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.obtenerEmpleaedoResponse> SoftProgWS.Empleados.EmpleadosWS.obtenerEmpleaedoAsync(SoftProgWS.Empleados.obtenerEmpleaedoRequest request)
        {
            return base.Channel.obtenerEmpleaedoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Empleados.obtenerEmpleaedoResponse> obtenerEmpleaedoAsync(int id)
        {
            SoftProgWS.Empleados.obtenerEmpleaedoRequest inValue = new SoftProgWS.Empleados.obtenerEmpleaedoRequest();
            inValue.id = id;
            return ((SoftProgWS.Empleados.EmpleadosWS)(this)).obtenerEmpleaedoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Empleados.eliminarEmpleadoResponse SoftProgWS.Empleados.EmpleadosWS.eliminarEmpleado(SoftProgWS.Empleados.eliminarEmpleadoRequest request)
        {
            return base.Channel.eliminarEmpleado(request);
        }
        
        public void eliminarEmpleado(int id)
        {
            SoftProgWS.Empleados.eliminarEmpleadoRequest inValue = new SoftProgWS.Empleados.eliminarEmpleadoRequest();
            inValue.id = id;
            SoftProgWS.Empleados.eliminarEmpleadoResponse retVal = ((SoftProgWS.Empleados.EmpleadosWS)(this)).eliminarEmpleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.eliminarEmpleadoResponse> SoftProgWS.Empleados.EmpleadosWS.eliminarEmpleadoAsync(SoftProgWS.Empleados.eliminarEmpleadoRequest request)
        {
            return base.Channel.eliminarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Empleados.eliminarEmpleadoResponse> eliminarEmpleadoAsync(int id)
        {
            SoftProgWS.Empleados.eliminarEmpleadoRequest inValue = new SoftProgWS.Empleados.eliminarEmpleadoRequest();
            inValue.id = id;
            return ((SoftProgWS.Empleados.EmpleadosWS)(this)).eliminarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Empleados.guardarEmpleadoResponse SoftProgWS.Empleados.EmpleadosWS.guardarEmpleado(SoftProgWS.Empleados.guardarEmpleadoRequest request)
        {
            return base.Channel.guardarEmpleado(request);
        }
        
        public void guardarEmpleado(SoftProgWS.Empleados.empleado empleado, SoftProgWS.Empleados.estado estado)
        {
            SoftProgWS.Empleados.guardarEmpleadoRequest inValue = new SoftProgWS.Empleados.guardarEmpleadoRequest();
            inValue.empleado = empleado;
            inValue.estado = estado;
            SoftProgWS.Empleados.guardarEmpleadoResponse retVal = ((SoftProgWS.Empleados.EmpleadosWS)(this)).guardarEmpleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.guardarEmpleadoResponse> SoftProgWS.Empleados.EmpleadosWS.guardarEmpleadoAsync(SoftProgWS.Empleados.guardarEmpleadoRequest request)
        {
            return base.Channel.guardarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Empleados.guardarEmpleadoResponse> guardarEmpleadoAsync(SoftProgWS.Empleados.empleado empleado, SoftProgWS.Empleados.estado estado)
        {
            SoftProgWS.Empleados.guardarEmpleadoRequest inValue = new SoftProgWS.Empleados.guardarEmpleadoRequest();
            inValue.empleado = empleado;
            inValue.estado = estado;
            return ((SoftProgWS.Empleados.EmpleadosWS)(this)).guardarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWS.Empleados.buscarEmpleadoPorDniResponse SoftProgWS.Empleados.EmpleadosWS.buscarEmpleadoPorDni(SoftProgWS.Empleados.buscarEmpleadoPorDniRequest request)
        {
            return base.Channel.buscarEmpleadoPorDni(request);
        }
        
        public SoftProgWS.Empleados.empleado buscarEmpleadoPorDni(string dni)
        {
            SoftProgWS.Empleados.buscarEmpleadoPorDniRequest inValue = new SoftProgWS.Empleados.buscarEmpleadoPorDniRequest();
            inValue.dni = dni;
            SoftProgWS.Empleados.buscarEmpleadoPorDniResponse retVal = ((SoftProgWS.Empleados.EmpleadosWS)(this)).buscarEmpleadoPorDni(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWS.Empleados.buscarEmpleadoPorDniResponse> SoftProgWS.Empleados.EmpleadosWS.buscarEmpleadoPorDniAsync(SoftProgWS.Empleados.buscarEmpleadoPorDniRequest request)
        {
            return base.Channel.buscarEmpleadoPorDniAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWS.Empleados.buscarEmpleadoPorDniResponse> buscarEmpleadoPorDniAsync(string dni)
        {
            SoftProgWS.Empleados.buscarEmpleadoPorDniRequest inValue = new SoftProgWS.Empleados.buscarEmpleadoPorDniRequest();
            inValue.dni = dni;
            return ((SoftProgWS.Empleados.EmpleadosWS)(this)).buscarEmpleadoPorDniAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmpleadosWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmpleadosWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.1:8080/SoftProgWS-1.0-SNAPSHOT/EmpleadosWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EmpleadosWSClient.GetBindingForEndpoint(EndpointConfiguration.EmpleadosWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EmpleadosWSClient.GetEndpointAddress(EndpointConfiguration.EmpleadosWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            EmpleadosWSPort,
        }
    }
}
