SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE LINEAORDENVENTA;
TRUNCATE TABLE ORDENVENTA;
TRUNCATE TABLE EMPLEADO;
TRUNCATE TABLE CLIENTE;
TRUNCATE TABLE PRODUCTO;
TRUNCATE TABLE CUENTA_USUARIO;
TRUNCATE TABLE AREA;

ALTER TABLE AREA AUTO_INCREMENT = 1;
ALTER TABLE EMPLEADO AUTO_INCREMENT = 1;
ALTER TABLE CLIENTE AUTO_INCREMENT = 1;
ALTER TABLE CUENTA_USUARIO AUTO_INCREMENT = 1;
ALTER TABLE PRODUCTO AUTO_INCREMENT = 1;
ALTER TABLE LINEAORDENVENTA AUTO_INCREMENT = 1;
ALTER TABLE ORDENVENTA AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
