//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgPruebas.SoftProgWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="SoftProgWS.CalculadoraWS")]
    public interface CalculadoraWS {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.softprog.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/sumarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/sumarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgPruebas.SoftProgWS.sumarResponse sumar(SoftProgPruebas.SoftProgWS.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/sumarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/sumarResponse")]
        System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.sumarResponse> sumarAsync(SoftProgPruebas.SoftProgWS.sumarRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.softprog.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/restarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/restarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgPruebas.SoftProgWS.restarResponse restar(SoftProgPruebas.SoftProgWS.restarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/restarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/restarResponse")]
        System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.restarResponse> restarAsync(SoftProgPruebas.SoftProgWS.restarRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.softprog.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/multiplicarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/multiplicarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgPruebas.SoftProgWS.multiplicarResponse multiplicar(SoftProgPruebas.SoftProgWS.multiplicarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/multiplicarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/multiplicarResponse")]
        System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.multiplicarResponse> multiplicarAsync(SoftProgPruebas.SoftProgWS.multiplicarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class sumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public sumarRequest() {
        }
        
        public sumarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class sumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public sumarResponse() {
        }
        
        public sumarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class restarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public restarRequest() {
        }
        
        public restarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class restarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public restarResponse() {
        }
        
        public restarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class multiplicarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public multiplicarRequest() {
        }
        
        public multiplicarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class multiplicarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public multiplicarResponse() {
        }
        
        public multiplicarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraWSChannel : SoftProgPruebas.SoftProgWS.CalculadoraWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraWSClient : System.ServiceModel.ClientBase<SoftProgPruebas.SoftProgWS.CalculadoraWS>, SoftProgPruebas.SoftProgWS.CalculadoraWS {
        
        public CalculadoraWSClient() {
        }
        
        public CalculadoraWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgPruebas.SoftProgWS.sumarResponse SoftProgPruebas.SoftProgWS.CalculadoraWS.sumar(SoftProgPruebas.SoftProgWS.sumarRequest request) {
            return base.Channel.sumar(request);
        }
        
        public int sumar(int a, int b) {
            SoftProgPruebas.SoftProgWS.sumarRequest inValue = new SoftProgPruebas.SoftProgWS.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            SoftProgPruebas.SoftProgWS.sumarResponse retVal = ((SoftProgPruebas.SoftProgWS.CalculadoraWS)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.sumarResponse> SoftProgPruebas.SoftProgWS.CalculadoraWS.sumarAsync(SoftProgPruebas.SoftProgWS.sumarRequest request) {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.sumarResponse> sumarAsync(int a, int b) {
            SoftProgPruebas.SoftProgWS.sumarRequest inValue = new SoftProgPruebas.SoftProgWS.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((SoftProgPruebas.SoftProgWS.CalculadoraWS)(this)).sumarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgPruebas.SoftProgWS.restarResponse SoftProgPruebas.SoftProgWS.CalculadoraWS.restar(SoftProgPruebas.SoftProgWS.restarRequest request) {
            return base.Channel.restar(request);
        }
        
        public int restar(int a, int b) {
            SoftProgPruebas.SoftProgWS.restarRequest inValue = new SoftProgPruebas.SoftProgWS.restarRequest();
            inValue.a = a;
            inValue.b = b;
            SoftProgPruebas.SoftProgWS.restarResponse retVal = ((SoftProgPruebas.SoftProgWS.CalculadoraWS)(this)).restar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.restarResponse> SoftProgPruebas.SoftProgWS.CalculadoraWS.restarAsync(SoftProgPruebas.SoftProgWS.restarRequest request) {
            return base.Channel.restarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.restarResponse> restarAsync(int a, int b) {
            SoftProgPruebas.SoftProgWS.restarRequest inValue = new SoftProgPruebas.SoftProgWS.restarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((SoftProgPruebas.SoftProgWS.CalculadoraWS)(this)).restarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgPruebas.SoftProgWS.multiplicarResponse SoftProgPruebas.SoftProgWS.CalculadoraWS.multiplicar(SoftProgPruebas.SoftProgWS.multiplicarRequest request) {
            return base.Channel.multiplicar(request);
        }
        
        public int multiplicar(int a, int b) {
            SoftProgPruebas.SoftProgWS.multiplicarRequest inValue = new SoftProgPruebas.SoftProgWS.multiplicarRequest();
            inValue.a = a;
            inValue.b = b;
            SoftProgPruebas.SoftProgWS.multiplicarResponse retVal = ((SoftProgPruebas.SoftProgWS.CalculadoraWS)(this)).multiplicar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.multiplicarResponse> SoftProgPruebas.SoftProgWS.CalculadoraWS.multiplicarAsync(SoftProgPruebas.SoftProgWS.multiplicarRequest request) {
            return base.Channel.multiplicarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgPruebas.SoftProgWS.multiplicarResponse> multiplicarAsync(int a, int b) {
            SoftProgPruebas.SoftProgWS.multiplicarRequest inValue = new SoftProgPruebas.SoftProgWS.multiplicarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((SoftProgPruebas.SoftProgWS.CalculadoraWS)(this)).multiplicarAsync(inValue);
        }
    }
}
